Models/Pizzas.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OnlinePizzaWebApplication.Models
{
    public class Pizzas
    {
        public Pizzas()
        {
            PizzaIngredients = new HashSet<PizzaIngredients>();
            Reviews = new HashSet<Reviews>();
        }

        public int Id { get; set; }

        [StringLength(100, MinimumLength = 2)]
        [RegularExpression("([a-zA-Z0-9 .&'-]+)", ErrorMessage = "The field Name should only include letters and number.")]
        [DataType(DataType.Text)]
        [Required]
        public string Name { get; set; }

        [Range(0, 1000000)]
        [DataType(DataType.Currency)]
        [Required]
        [Precision(18, 2)]
        public decimal Price { get; set; }

        [StringLength(255, MinimumLength = 2)]
        [DataType(DataType.MultilineText)]
        [Required]
        public string Description { get; set; }

        [DataType(DataType.ImageUrl)]
        public string ImageUrl { get; set; }

        public bool IsPizzaOfTheWeek { get; set; }

        [DisplayName("Select Category")]
        public int CategoriesId { get; set; }

        public virtual Categories Category { get; set; }

        public virtual ICollection<PizzaIngredients> PizzaIngredients { get; set; }
        public virtual ICollection<Reviews> Reviews { get; set; }

    }
}

ViewModels/SearchPizzasViewModel.cs
using OnlinePizzaWebApplication.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OnlinePizzaWebApplication.ViewModels
{
    public class SearchPizzasViewModel
    {
        [Required]
        [DisplayName("Serach")]
        public string SearchText { get; set; }

        //public IEnumerable<string> SearchListExamples { get; set; }

        public IEnumerable<Pizzas> PizzaList { get; set; }

    }
}

Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlinePizzaWebApplication.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using OnlinePizzaWebApplication.Data;

namespace OnlinePizzaWebApplication.Controllers
{
    [Authorize]
    public class ReviewsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public ReviewsController(AppDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AdminIndex()
        {
            var reviews = await _context.Reviews.Include(r => r.Pizza).Include(r => r.User).ToListAsync();
            return View(reviews);
        }

        // GET: Reviews
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            bool isAdmin = await _userManager.IsInRoleAsync(user, "Admin");

            if (isAdmin)
            {
                var allReviews = _context.Reviews.Include(r => r.Pizza).Include(r => r.User).ToList();
                return View(allReviews);
            }
            else
            {
                var reviews = _context.Reviews.Include(r => r.Pizza).Include(r => r.User)
                    .Where(r => r.User == user).ToList();
                return View(reviews);
            }
        }

        // GET: Reviews
        [AllowAnonymous]
        public async Task<IActionResult> ListAll()
        {
            var reviews = await _context.Reviews.Include(r => r.Pizza).Include(r => r.User).ToListAsync();
            return View(reviews);
        }

        private async Task<List<Reviews>> SortReviews(string sortBy, bool isDescending)
        {
            var reviewsList = _context.Reviews.Include(r => r.Pizza).Include(r => r.User);
            IQueryable<Reviews> result;

            if (sortBy == null || sortBy == "")
            {
                result = reviewsList;
            }

            if (isDescending == false)
            {
                result = sortBy.ToLower() switch
                {
                    "date" => reviewsList.OrderBy(x => x.Date),
                    "grade" => reviewsList.OrderBy(x => x.Grade),
                    "title" => reviewsList.OrderBy(x => x.Title),
                    "pizza name" => reviewsList.OrderBy(x => x.Pizza.Name),
                    _ => reviewsList.OrderBy(x => x.Pizza.Id),
                };
            }
            else
            {
                result = sortBy.ToLower() switch
                {
                    "date" => reviewsList.OrderByDescending(x => x.Date),
                    "grade" => reviewsList.OrderByDescending(x => x.Grade),
                    "title" => reviewsList.OrderByDescending(x => x.Title),
                    "pizza name" => reviewsList.OrderByDescending(x => x.Pizza.Name),
                    _ => reviewsList.OrderByDescending(x => x.Pizza.Id),
                };
            }

            //Partial view?
            return await result.ToListAsync();
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> AjaxListReviews(string sortBy, bool isDescending)
        {
            var listOfReviews = await SortReviews(sortBy, isDescending);

            return PartialView(listOfReviews);
        }

        // GET: Reviews
        [AllowAnonymous]
        public async Task<IActionResult> PizzaReviews(int? pizzaId)
        {
            if (pizzaId == null)
            {
                return NotFound();
            }
            var pizza = _context.Pizzas.FirstOrDefault(x => x.Id == pizzaId);
            if (pizza == null)
            {
                return NotFound();
            }
            var reviews = await _context.Reviews.Include(r => r.Pizza).Include(r => r.User).Where(x => x.Pizza.Id == pizza.Id).ToListAsync();
            if (reviews == null)
            {
                return NotFound();
            }
            ViewBag.PizzaName = pizza.Name;
            ViewBag.PizzaId = pizza.Id;

            return View(reviews);
        }

        // GET: Reviews/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reviews = await _context.Reviews
                .Include(r => r.Pizza)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (reviews == null)
            {
                return NotFound();
            }

            return View(reviews);
        }

        // GET: Reviews/Create
        public IActionResult CreateWithPizza(int? pizzaId)
        {
            var review = new Reviews();

            if (pizzaId == null)
            {
                return NotFound();
            }

            var pizza = _context.Pizzas.FirstOrDefault(p => p.Id == pizzaId);
            
            if (pizza == null)
            {
                return NotFound();
            }

            review.Pizza = pizza;
            review.PizzaId = pizza.Id;
            ViewData["PizzaId"] = new SelectList(_context.Pizzas.Where(p => p.Id == pizzaId), "Id", "Name");
            var listOfNumbers = new List<int>() { 1, 2, 3, 4, 5 };
            var listOfGrades = listOfNumbers.Select(x => new { Id = x, Value = x.ToString() });
            ViewData["Grade"] = new SelectList(listOfGrades, "Id", "Value");

            return View(review);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateWithPizza(int pizzaId, Reviews reviews)
        {
            if (pizzaId != reviews.PizzaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(HttpContext.User);
                reviews.UserId = userId;
                reviews.Date = DateTime.Now;

                _context.Add(reviews);
                await _context.SaveChangesAsync();
                return Redirect($"PizzaReviews?pizzaId={pizzaId}");
            }
            var listOfNumbers = new List<int>() { 1, 2, 3, 4, 5 };
            var listOfGrades = listOfNumbers.Select(x => new { Id = x, Value = x.ToString() });
            ViewData["Grade"] = new SelectList(listOfGrades, "Id", "Value", reviews.Grade);
            ViewData["PizzaId"] = new SelectList(_context.Pizzas.Where(p => p.Id == pizzaId), "Id", "Name", reviews.PizzaId);
            return View(reviews);
        }

        // GET: Reviews/Create
        public IActionResult Create()
        {
            var listOfNumbers = new List<int>() { 1, 2, 3, 4, 5 };
            var listOfGrades = listOfNumbers.Select(x => new { Id = x, Value = x.ToString() });
            ViewData["Grade"] = new SelectList(listOfGrades, "Id", "Value");
            ViewData["PizzaId"] = new SelectList(_context.Pizzas, "Id", "Name");
            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Grade,PizzaId")] Reviews reviews)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(HttpContext.User);
                reviews.UserId = userId;

                reviews.Date = DateTime.Now;
                _context.Add(reviews);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            var listOfNumbers = new List<int>() { 1, 2, 3, 4, 5 };
            var listOfGrades = listOfNumbers.Select(x => new { Id = x, Value = x.ToString() });
            ViewData["Grade"] = new SelectList(listOfGrades, "Id", "Value", reviews.Grade);
            ViewData["PizzaId"] = new SelectList(_context.Pizzas, "Id", "Name", reviews.PizzaId);
            
            return View(reviews);
        }

        // GET: Reviews/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reviews = await _context.Reviews.SingleOrDefaultAsync(m => m.Id == id);
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var userRoles = await _userManager.GetRolesAsync(user);
            bool isAdmin = userRoles.Any(r => r == "Admin");

            if (reviews == null)
            {
                return NotFound();
            }

            if (isAdmin == false)
            {
                var userId = _userManager.GetUserId(HttpContext.User);
                if (reviews.UserId != userId)
                {
                    return BadRequest("You do not have permissions to edit this review.");
                }
            }
            var listOfNumbers = new List<int>() { 1, 2, 3, 4, 5 };
            var listOfGrades = listOfNumbers.Select(x => new { Id = x, Value = x.ToString() });
            ViewData["Grade"] = new SelectList(listOfGrades, "Id", "Value", reviews.Grade);
            ViewData["PizzaId"] = new SelectList(_context.Pizzas, "Id", "Name", reviews.PizzaId);
            return View(reviews);
        }

        // POST: Reviews/Edit/5

Views/Pizzas/AjaxSearchList.cshtml
@model List<Pizzas>

<h4>Search Results</h4>

@if (Model.Any())
{
    <div id="SearchResultsPizzaSummaryId" class="card-container">
        @foreach (var pizza in Model)
        {
            @await Html.PartialAsync("PizzaSummary", pizza)
        }
    </div>
}
else
{
    <p>No pizzas found.</p>
}

Views/Pizzas/Create.cshtml
@model OnlinePizzaWebApplication.Models.Pizzas

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create" enctype="multipart/form-data" method="post">
    <div class="form-horizontal">
        <h4>Pizzas</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Price" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Description" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ImageUrl" class="col-md-2 control-label">Upload Image</label>
            <div class="col-md-10">
                <input asp-for="ImageUrl" type="file" class="form-control-file" accept="image/*" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    <input asp-for="IsPizzaOfTheWeek" />
                    <label asp-for="IsPizzaOfTheWeek"></label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CategoriesId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="CategoriesId" class="form-control" asp-items="ViewBag.CategoriesId"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div class="form-group row mt-4">
    <div class="offset-md-2 col-md-10">
        <a asp-action="Index" class="btn btn-secondary ml-2">Back to List</a>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Pizzas/Delete.cshtml
@model OnlinePizzaWebApplication.Models.Pizzas

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pizzas</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="Id" />
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsPizzaOfTheWeek)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsPizzaOfTheWeek)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

Views/Pizzas/Details.cshtml
@model Pizzas

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div class="form-horizontal">
    <h4>Pizzas</h4>
    <hr />

    <div class="form-group">
        <label class="col-md-2 control-label">@Html.DisplayNameFor(model => model.Name)</label>
        <div class="col-md-10 form-control-static">
            @Html.DisplayFor(model => model.Name)
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-2 control-label">@Html.DisplayNameFor(model => model.Price)</label>
        <div class="col-md-10 form-control-static">
            @Html.DisplayFor(model => model.Price)
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-2 control-label">@Html.DisplayNameFor(model => model.Description)</label>
        <div class="col-md-10 form-control-static">
            @Html.DisplayFor(model => model.Description)
        </div>
    </div>

    @if (!string.IsNullOrEmpty(Model.ImageUrl))
    {
        <div class="form-group">
            <label class="col-md-2 control-label">@Html.DisplayNameFor(model => model.ImageUrl)</label>
            <div class="col-md-10">
                <img src="@Model.ImageUrl" alt="Pizza Image" class="img-thumbnail" style="max-height:150px;" />
            </div>
        </div>
    }

    <div class="form-group">
        <label class="col-md-2 control-label">@Html.DisplayNameFor(model => model.IsPizzaOfTheWeek)</label>
        <div class="col-md-10 form-control-static">
            @Html.DisplayFor(model => model.IsPizzaOfTheWeek)
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-2 control-label">@Html.DisplayNameFor(model => model.Category)</label>
        <div class="col-md-10 form-control-static">
            @Html.DisplayFor(model => model.Category.Name)
        </div>
    </div>
</div>

<div class="form-group row mt-4">
    <div class="offset-md-2 col-md-10">
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
        <a asp-action="Index" class="btn btn-secondary ml-2">Back to List</a>
    </div>
</div>

Views/Pizzas/DisplayDetails.cshtml
@model Pizzas

@{
    var ModelName = "Pizza Details";
    ViewData["Title"] = ModelName;
}

<h2>@ModelName</h2>
<hr />

<p>
    <a asp-action="ListAll">Back to List</a>
</p>

<div class="thumbnail">
    <img alt="@Model.Name" src="@Model.ImageUrl" height="800" width="800" class="img-responsive" >
    <div class="caption-full">
        <h2 class="pull-right">@Model.Price.ToString("c")</h2>
        <h2>
            <a href="">@Model.Name</a>
        </h2>
        <div>
        <h4>Category: <b> @Model.Category.Name </b></h4>
        <p>@Model.Description</p>
        <p>
            <h4><b>List of Ingredients:</b></h4>

            @if (ViewBag.PizzaIngredients.Count > 0)
        {
                @foreach (var ing in ViewBag.PizzaIngredients)
            {
                    <div> @ing </div>
                }
            }
            else
            {
                <div>No @Html.DisplayNameFor(Model => Model.PizzaIngredients) was found. </div>
            }
        </p>
        <p>
        @if (ViewBag.AverageReviewScore > 0)
        {
            <h4>Average Review Score: <b> @ViewBag.AverageReviewScore </b></h4>
        }
        else
        {
            <h4>No Reviews was found. </h4>
        }

        @if (ViewBag.AverageReviewScore <= 0 || ViewBag.AverageReviewScore > 5)
        {
            <img class="review-stars" src="~/images/0stars.png" alt="No Reviews was found." />
        }
        else if (ViewBag.AverageReviewScore > 4.5)
        {
            <img class="review-stars" src="~/images/5stars.png" alt="5 stars picture." />
        }
        else if (ViewBag.AverageReviewScore > 4.0)
        {
            <img class="review-stars" src="~/images/4.5stars.png" alt="4.5 stars picture." />
        }
        else if (ViewBag.AverageReviewScore > 3.5)
        {
            <img class="review-stars" src="~/images/4stars.png" alt="4 stars picture." />
        }
        else if (ViewBag.AverageReviewScore > 3.0)
        {
            <img class="review-stars" src="~/images/3.5stars.png" alt="3.5 stars picture." />
        }
        else if (ViewBag.AverageReviewScore > 2.5)
        {
            <img class="review-stars" src="~/images/3stars.png" alt="3 stars picture." />
        }
        else if (ViewBag.AverageReviewScore > 2.0)
        {
            <img class="review-stars" src="~/images/2.5stars.png" alt="2.5 stars picture." />
        }
        else if (ViewBag.AverageReviewScore > 1.5)
        {
            <img class="review-stars" src="~/images/2stars.png" alt="2 stars picture." />
        }
        else if (ViewBag.AverageReviewScore > 1.0)
        {
            <img class="review-stars" src="~/images/1.5stars.png" alt="1.5 stars picture." />
        }
        else
        {
            <img class="review-stars" src="~/images/1star.png" alt="1 star picture." />
        }

        </p>
            <h3>Customer Reviews</h3>
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="card shadow-sm mb-4">
                        <div class="card-body">
                            <form asp-action="CreateWithPizza" asp-controller="Reviews" method="post">
                                <input type="hidden" name="PizzaId" value="@Model.Id" />

                                <div class="mb-3">
                                    <label for="Title" class="form-label fw-bold">Review Title</label>
                                    <input name="Title" id="Title" class="form-control" placeholder="Enter your review title" required />
                                </div>

                                <div class="mb-3">
                                    <label for="Description" class="form-label fw-bold">Description</label>
                                    <textarea name="Description" id="Description" class="form-control" rows="3" placeholder="Write your detailed feedback" required></textarea>
                                </div>

                                <div class="mb-3">
                                    <label for="Grade" class="form-label fw-bold">Rating</label>
                                    <select name="Grade" id="Grade" class="form-select" required>
                                        <option value="">-- Select rating --</option>
                                        @for (int i = 1; i <= 5; i++)
                                        {
                                            <option value="@i">@i Star@(i > 1 ? "s" : "")</option>
                                        }
                                    </select>
                                </div>

                                <button type="submit" class="btn btn-success w-100">
                                    <i class="bi bi-check-circle"></i> Submit Review
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>


            <!-- Hiển thị danh sách review -->
            @if (ViewBag.Reviews != null && ((List<Reviews>)ViewBag.Reviews).Count > 0)
            {
                <table class="table">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Grade</th>
                            <th>Date</th>
                            <th>Pizza</th>
                            <th>User</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in (List<Reviews>)ViewBag.Reviews)
                        {
                            <tr>
                                <td>@item.Title</td>
                                <td>@item.Description</td>
                                <td>@item.Grade</td>
                                <td>@item.Date.ToString("dd/MM/yyyy")</td>
                                <td>@item.Pizza.Name</td>
                                <td>@item.User?.Email</td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <p>No reviews found for this pizza.</p>
            }


        <br />
        <p class="button">
            <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart"
                asp-route-pizzaId="@Model.Id">Add Pizza</a>
        </p>
    </div>
</div>

Views/Pizzas/Edit.cshtml
@model OnlinePizzaWebApplication.Models.Pizzas

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit" enctype="multipart/form-data" method="post">
    <div class="form-horizontal">
        <h4>Pizzas</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />

        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Price" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Description" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="ImageUrl" class="col-md-2 control-label">Upload Image</label>
            <div class="col-md-10">
                <input asp-for="ImageUrl" type="file" class="form-control-file" accept="image/*" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
        </div>

        @if (!string.IsNullOrEmpty(Model.ImageUrl))
        {
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <img src="@Model.ImageUrl" alt="Pizza Image" style="max-height:150px;" class="img-thumbnail" />
                </div>
            </div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    <input asp-for="IsPizzaOfTheWeek" />
                    <label asp-for="IsPizzaOfTheWeek"></label>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="CategoriesId" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="CategoriesId" class="form-control" asp-items="ViewBag.CategoriesId"></select>
                <span asp-validation-for="CategoriesId" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div class="form-group row mt-4">
    <div class="offset-md-2 col-md-10">
        <a asp-action="Index" class="btn btn-secondary ml-2">Back to List</a>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Pizzas/Index.cshtml
@model IEnumerable<Pizzas>

@{
    var pageName = "Pizzas";
    ViewData["Title"] = pageName;
}

<h2>@pageName</h2>

<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
    @*<a asp-action="Create" class="btn btn-primary">Create New</a>
    <a asp-action="Create" class="btn btn-danger">Create New</a>
    <a asp-action="Create" class="btn btn-default">Create New</a>
    <a asp-action="Create" class="btn btn-info">Create New</a>
    <a asp-action="Create" class="btn btn-success">Create New</a>
    <a asp-action="Create" class="btn btn-warning">Create New</a>*@
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ImageUrl)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsPizzaOfTheWeek)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <img src="@item.ImageUrl" alt="@item.Name" style="max-height:100px;" />
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.IsPizzaOfTheWeek)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" title="Edit">
                        <i class="fas fa-edit"></i>
                    </a> |
                    <a asp-action="Details" asp-route-id="@item.Id" title="Details">
                        <i class="fas fa-info-circle"></i>
                    </a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" title="Delete">
                        <i class="fas fa-trash-alt text-danger"></i>
                    </a>
                </td>

        </tr>
}
    </tbody>
</table>

Views/Pizzas/ListAllOld.cshtml
@model IEnumerable<Pizzas>

@{
    var ModelName = "Search Pizzas";
    ViewData["Title"] = ModelName;
}

<h2>@ModelName</h2>
<hr />



<div id="PizzaSummaryId" class="card-container">
    @foreach (var pizza in Model)
    {
        @await Html.PartialAsync("PizzaSummary", pizza)
    }
</div>
    
<br />